site_name: Python Training for Devops.
nav:
  - Home: index.md
  - Python Syntax: syntax.md
  - Memory Management: mem.md
  - Global Interpreter Lock: gil.md
  - Object Oriented Programming: oops.md
  - Basic Tooling for Python: tooling.md
  - Creating a CLI application: cliapp.md
theme: 
  name: material